
# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data

sass:
 sass_dir:    _sass
 style:       compressed
 
# custom
archive_path:    /archive.html
categories_path: /categories.html
tags_path:       /tags.html
atom_path:       /atom.xml
rss_path:        /rss.xml

collections:
 docs:
  output:    true
  permalink: /docs/:path/

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      [Gemfile.lock, Gemfile,README.md,LICENSE.md,LICENSE,CNAME,Rakefile]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"


# Filtering Content
show_drafts: true
limit_posts: 0
future:      true
unpublished: false
live:        false

# Plugins
whitelist: []
gems:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         true
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    9510
host:    0.0.0.0
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     /:categories/:year/:month/:title/
paginate_path: /page:num


quiet:    false

defaults: 
  -
    scope:
     path: ""
     type: "posts"
    values:
     layout: "blog"
  -
    scope:
     path: "projects"
     type: "pages"
    values:
     layout: "project" # overrides previous default layout
  -
    scope:
     path: _posts/en
    values:
     layout: default
     lang: en
  -
    scope:
     path: _posts/vn
    values:
     layout: default
     lang: vn    

