# Dependencies
# markdown:         redcarpet
# highlighter:	pygments

# Permalinks
permalink:        none

# Setup
title:            Ba Si Duong
tagline:          'Blog'
description:      'Ba Si Duong Blog'
url:              https://basiduong.com
baseurl:          '/'
paginate:         5

author:
  name:           'Ba Si Duong'
  url:            https://twitter.com/basiduong

# Custom vars
version:          1.0.2

github:
  repo:           https://github.com/BaSiDuong/basiduong.github.io

exclude: Gemfile.lock, Gemfile
timezone: Asia/Ho_Chi_Minh
