# Dependencies
markdown:         redcarpet
highlighter:	pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ba Si Duong
tagline:          'Blog'
description:      'Ba Si Duong Blog'
url:              http://www.basiduong.com
baseurl:          '/'
paginate:         5

author:
  name:           'Ba Si Duong'
  url:            https://twitter.com/basiduong

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/BaSiDuong/basiduong.github.io
